version: "3"
services:
  qtangle:
    build: "."
    container_name: qtangle
    environment:
      QTANGLE__LOG: "info"
      QTANGLE__QBITTORRENT__API_URL: "http://qbittorrent:9618"
      QTANGLE__QBITTORRENT__PASSWORD: "password"
      QTANGLE__QBITTORRENT__USERNAME: "username"
    volumes:
      - ./qtangle.toml:/app/qtangle.toml
      - ./test/qtangle:/qtangle
    # Setup the internal environment for testing.
    # This shouldn't be needed for production use.
    command:
      - "sh"
      - "-c"
      - "ln -s /qtangle/downloads /downloads && ln -s /qtangle/media /app/media && ./qtangle"
    depends_on:
      - qbittorrent

  # Wiremock is being used here for testing purposes.
  # An actual qBittorrent container can be used as a drop-in replacement.
  qbittorrent:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    volumes:
      - ./test/wiremock:/home/wiremock
    environment:
      WIREMOCK_OPTIONS: "--port 9618"
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]